name: api-core

on: [push]

jobs:

  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Discord notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      #- name: Install Composer excutable
      #  run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer && chmod 755 /usr/bin/composer
      - name: Install Composer dependencies
        run: composer install --prefer-dist
      - name: Run tests
        run: ./vendor/bin/phpunit
